### ISSUE TITLE
Add support for WWN, OSE, and SWADE

### ISSUE THREAD

**Issue by sirkerry** [sweetrpg/lootparcels-foundryvtt#32]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Would like to see support for Worlds Without Number (WWN), Old School Essentials (OSE), and Savage Worlds Adventure Edition (SWADE) added Loot Parcels.

**Comment by paulyhedral** [comment]
@sirkerry Do you have a link for the OSE and SWADE systems? I do not see them in the Foundry registry.

**Comment by sirkerry** [comment]
Oh, yeah that might be difficult currently - I think SWADE is about 4 to 6 weeks from having v12 support, not sure what OSE's v12 support status is.
