### ISSUE TITLE
Problems upgrading to 0.15 and then error messages

### ISSUE THREAD

**Issue by apoapostolov** [sweetrpg/lootparcels-foundryvtt#33]
Updating from 0.13 to 0.15 causes error after the "manifest migration" dialog. 

Even after manually deleting the module and installing 0.15 there are issues

![image](https://github.com/sweetrpg/lootparcels-foundryvtt/assets/4083812/936c0d75-d971-420c-bea1-fdbe49a92923)

**Comment by paulyhedral** [comment]
Sorry about that. I transposed the `download` and `latest` parts of the path. They are reversed when using `latest` vs. a specific version.
